### PR TITLE
Update compress_spooler.rb

### PR DESCRIPTION
**Pull request by Bradox**
Fixes issues #2 and #3

### CODE REVIEW

**Comment by jsvd** [comment]
The code looks good, would be nice to have 3 tests: 2 for encode/decode, and one for the buffer fix.

1. decode an event w/ a float "@timestamp_f" field => check if the "@timestamp" field is correct and "@timestamp_f" is no longer there
2. encode a simple event => check if "@timestamp_f" has a correct float and "@timestamp" isn't there
3. send X events that fill the buffer and see that the flush happens at the Xth instead of X+1th

**Comment by Bradox** [comment]
Hello, I am not much of a ruby developer, so if you tell me how to write the test I will do so. Or point out where to learn to do them.
Thanks

**Comment by jsvd** [comment]
For decode test, you can see examples in https://github.com/logstash-plugins/logstash-codec-cef/blob/master/spec/codecs/cef_spec.rb#L16-L31

For encode, https://github.com/logstash-plugins/logstash-codec-rubydebug/blob/master/spec/codecs/rubydebug_spec.rb#L14-L25

The [line codec](https://github.com/logstash-plugins/logstash-codec-line/blob/master/spec/codecs/line_spec.rb) also has good specs for encode/decode.

I'm available to further help you with this :)

**Comment by jsvd** [comment]
@Bradox do you need any other help to make the tests for this? we can meet on irc if you want

**Comment by purbon** [comment]
@Bradox I apologies It took really longs for us to come back here. Logstash took a quite big chance of changes, so I updated the code in this PR, and merged it together with some tests at #7. Thanks for your contribution, is much appreciate it!

- purbon

@Bradox Let me know if you got more data on the timestamp issue, for now I can not reproduce it, looking forward to get more data on it.

**Pull request closed without merging**
